# url: 'http://delphi.org'
url: "https://delphiorg.github.io/"
title: 'The Podcast at Delphi.org'
description: 'The Podcast about the Delphi programming language, tools, news and community.'
baseurl: ""
permalink: /:title/
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap    
  - jekyll-seo-tag
kramdown:
  syntax_highlighter_opts:
    disable: true
exclude:
  - _scripts/
  - vendor/       
  - Gemfile.lock